export { default as App } from './App';
export * from './Intercepts/getInfoAdministrador';
export * from './Models';
export { default as ErrorPage } from './Pages/404/ErrorPage';
export * from './Pages/Index';
export { default as Admin } from './Pages/private/admin/Admin';
export { default as Barberos } from './Pages/private/admin/components/Barberos';
export { default as Dashboard } from './Pages/private/admin/components/Dashboard';
export { default as Servicios } from './Pages/private/admin/components/Servicios';
export { default as Login } from './Pages/private/log/components/Login';
export { default as login } from './Pages/private/log/login';
export { default as Turno } from './Pages/view/turn/Turno';
export { default as Calendario } from './Pages/view/turn/components/Calendario';
export { default as FormularioTurno } from './Pages/view/turn/components/FormularioTurno';
export * from './main';
export { default as Root } from './routes/Root';
